# Generated by Django 5.0.4 on 2024-04-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dic',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
